from sqlalchemy import Column, create_engine
from sqlalchemy import Column, ForeignKey, Integer, String,Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class ReadingAverage(Base):
    __tablename__ = 'readingaverage'

    id = Column(Integer,primary_key=True)
    Vehicle_Number = Column(String(255))
    Ambiant_Pressure = Column(Float)
    Canister_Controler = Column(Float)
    Current_for_Injector_Opening = Column(Float)
    Distance_Km = Column(Float)
    Lambda_Adapation = Column(Float)
    Gear_Engaged = Column(Float)
    Lambda_Control_1 = Column(Float)
    Lambda_Control_2 = Column(Float)
    MAF_Before_Compressor = Column(Float)
    Engine_MAF = Column(Float)
    Fuel_Mass_Adapation = Column(Float)
    Engine_Speed = Column(Float)
    Turbo_Turbine_Speed = Column(Float)
    Injection_Number = Column(Float)
    Fuel_Pressure_at_Inlet_Pump = Column(Float)
    Fuel_Pressure = Column(Float)
    Turbo_Waste_Gate_Position = Column(Float)
    Pedal_Position = Column(Float)
    Turbo_Waste_Gate_Controler = Column(Float)
    Water_Pump_Controler = Column(Float)
    Engine_Thermostat_Controler = Column(Float)
    Engine_Air_Throttle_Controler = Column(Float)
    Fuel_Pump_Delivery = Column(Float)
    Segment_Number = Column(Float)
    Injector_Adapation1 = Column(Float)
    Injector_Adapation2 = Column(Float)
    Injector_Adapation3 = Column(Float)
    Injector_Adapation4 = Column(Float)
    Injector_Adapation5 = Column(Float)
    Injector_Adapation6 = Column(Float)
    Injector_Adapation7 = Column(Float)
    Injector_Adapation8 = Column(Float)
    Injector_Adapation9 = Column(Float)
    Injector_Adapation10 = Column(Float)
    Injector_Adapation11 = Column(Float)
    Injector_Adapation12 = Column(Float)
    Injector_Adapation13 = Column(Float)
    Injector_Adapation14 = Column(Float)
    Injector_Adapation15 = Column(Float)
    Injector_Adapation16 = Column(Float)
    Injector_Adapation17 = Column(Float)
    Injector_Adapation18 = Column(Float)
    Injector_Adapation19 = Column(Float)
    Injector_Adapation20 = Column(Float)
    Current_Time_for_Injector = Column(Float)
    Pump_Adaptation_2 = Column(Float)
    Ambiant_Temperature = Column(Float)
    Engine_Coolant_Tempertaure = Column(Float)
    ECU_Temperature = Column(Float)
    TUrbo_Temperature_before_Turbine = Column(Float)
    Fuel_Temperature_Before_Pump = Column(Float)
    Fuel_Temperature_at_Pump_Outlet = Column(Float)
    Fuel_Temperature_In_Rail = Column(Float)
    Engine_Inlet_Temperture = Column(Float)
    time_30_s = Column(Float)
    timestamp = Column(Integer)
    Engine_Oil_Temperature = Column(Float)
    Trt = Column(Float)
    Battery_Voltage = Column(Float)
    Voltage_Boost_Injector_control = Column(Float)
    Pump_Adaptation_1 = Column(Float)
    Waste_Gate_Adapatation_1 = Column(Float)
    Waste_Gate_Adapatation_2 = Column(Float)
    Vehicle_Speed = Column(Float)

class Reading(Base):
    __tablename__ = 'reading'

    id = Column(Integer,primary_key=True)
    vehicle_number = Column(String(255))
    ambiant_pressure = Column(Float)
    canister_controler = Column(Float)
    current_for_injector_opening = Column(Float)
    distance_km = Column(Float)
    lambda_adapation = Column(Float)
    gear_engaged = Column(Float)
    lambda_control_1 = Column(Float)
    lambda_control_2 = Column(Float)
    maf_before_compressor = Column(Float)
    engine_maf = Column(Float)
    fuel_mass_adapation = Column(Float)
    engine_speed = Column(Float)
    turbo_turbine_speed = Column(Float)
    injection_number = Column(Float)
    fuel_pressure_at_inlet_pump = Column(Float)
    fuel_pressure = Column(Float)
    turbo_waste_gate_position = Column(Float)
    pedal_position = Column(Float)
    turbo_waste_gate_controler = Column(Float)
    water_pump_controler = Column(Float)
    engine_thermostat_controler = Column(Float)
    engine_air_throttle_controler = Column(Float)
    fuel_pump_delivery = Column(Float)
    segment_number = Column(Float)
    injector_adapation1 = Column(Float)
    injector_adapation2 = Column(Float)
    injector_adapation3 = Column(Float)
    injector_adapation4 = Column(Float)
    injector_adapation5 = Column(Float)
    injector_adapation6 = Column(Float)
    injector_adapation7 = Column(Float)
    injector_adapation8 = Column(Float)
    injector_adapation9 = Column(Float)
    injector_adapation10 = Column(Float)
    injector_adapation11 = Column(Float)
    injector_adapation12 = Column(Float)
    injector_adapation13 = Column(Float)
    injector_adapation14 = Column(Float)
    injector_adapation15 = Column(Float)
    injector_adapation16 = Column(Float)
    injector_adapation17 = Column(Float)
    injector_adapation18 = Column(Float)
    injector_adapation19 = Column(Float)
    injector_adapation20 = Column(Float)
    current_time_for_injector = Column(Float)
    pump_adaptation_2 = Column(Float)
    ambiant_temperature = Column(Float)
    engine_coolant_tempertaure = Column(Float)
    ecu_temperature = Column(Float)
    turbo_temperature_before_turbine = Column(Float)
    fuel_temperature_before_pump = Column(Float)
    fuel_temperature_at_pump_outlet = Column(Float)
    fuel_temperature_in_rail = Column(Float)
    engine_inlet_temperture = Column(Float)
    time_30_s = Column(Float)
    timestamp = Column(Float)
    engine_oil_temperature = Column(Float)
    trt = Column(Float)
    battery_voltage = Column(Float)
    voltage_boost_injector_control = Column(Float)
    pump_adaptation_1 = Column(Float)
    waste_gate_adapatation_1 = Column(Float)
    waste_gate_adapatation_2 = Column(Float)
    vehicle_speed = Column(Float)
    vin = Column(String(255))

engine = create_engine('mysql+pymysql://mysql:mysql@192.168.0.102:12346/datacrawlingkraken')
print("Engine created....")

# Create all tables in the engine. This is equivalent to "Create Table"
# statements in raw SQL.
Base.metadata.create_all(engine)
print("Create all tables done....")